### PR TITLE
Editor image support

### PR DESCRIPTION
**Pull request by rama-pang**
Notes:
- Paste image functionality will trigger only when there is no text in clipboard; i.e., `clipboard.getData("text").length === 0` is satisfied.
- On paste, the editor will upload the image file  to firebase storage, and insert the text `` to the editor.

### CODE REVIEW

**Comment by Berted** [comment]
Some comments:
- No user feedback in regards to when file is uploading.
- Image copy-ing on Firefox still broken if copying from Windows.
- Firebase Cloud Storage security rules is a bit.... yikes rn.

**Comment by Berted** [comment]
Resolves #42.

**Comment by rama-pang** [comment]
Notes:
- Added a toast notification when a file is being uploaded.
- Modified the image storage location in Firebase Cloud Storage. Images are saved in `docs/{docID}/{image_name}`.

**Comment by rama-pang** [comment]
Notes:
- Added an icon on the document editor navigation bar, which opens the "Image bank" drawer.
- Users can upload image from their computers using the upload button (in addition to the "paste image" function).
- All images uploaded and pasted will be displayed in the drawer.
- There is a copy button on the bottom right of each image. If clicked, it will copy the markdown syntax to display that image to the clipboard.
- There is a delete button on the bottom right of each image. Only document owners can delete images.

**Comment by Berted** [comment]
- Image drawer has been removed from viewers since there's no point for viewers to be able to see the drawer.
- The copy and delete buttons has been modified to increase visibility.

**Comment by Berted** [comment]
Great! will merge now.

**Pull request merged**
