### PR TITLE
Add search bar

### LINKED ISSUE #71: Add note search feature
I think this feature is missing

### PR DESCRIPTION
**Pull request by rama-pang**
When searching for a title `search`, a document with title `title` will be included if `title.includes(search)`, ignoring upper/lowercase.

Closes #71.

### CODE REVIEW

**Comment by Berted** [comment]
Looks good, some comments:

- Search field seems to default to "time-dec" as its value.
- Perhaps we should modify the empty docs placeholder text when search/filters are active
- Would be nice if the substring is highlighted? (Can use chakra ui's new highlight feature, would need to update chakra ui first)

**Comment by rama-pang** [comment]
Notes:
- ~~Search field seems to default to "time-dec" as its value.~~ Fixed issue.
- ~~Perhaps we should modify the empty docs placeholder text when search/filters are active~~ Added the placeholder text `No matches found!`. Could be changed later if needed.
- ~~Would be nice if the substring is highlighted? (Can use chakra ui's new highlight feature, would need to update chakra ui first)~~ Updated chakra ui (hopefully nothing breaks), and added the highlight substring feature.

**Comment by Berted** [comment]
> Notes:
> 
> * ~Search field seems to default to "time-dec" as its value.~ Fixed issue.
> * ~Perhaps we should modify the empty docs placeholder text when search/filters are active~ Added the placeholder text `No matches found!`. Could be changed later if needed.
> * ~Would be nice if the substring is highlighted? (Can use chakra ui's new highlight feature, would need to update chakra ui first)~ Updated chakra ui (hopefully nothing breaks), and added the highlight substring feature.

For the second point, filter active check is not performed. Otherwise, looks great!

**Comment by rama-pang** [comment]
Fixed the filter active check.

**Pull request merged**
