### PR TITLE
Add edit user profile functionality

### PR DESCRIPTION
**Pull request by rama-pang**
Notes:
- Added edit button besides logout button.
- Can edit name.
- In Progress: upload profile picture functionality.

### CODE REVIEW

**Comment by Berted** [comment]
Perhaps it'll be better to change the current Popover design to a cleaner Menu interface. (As can be seen from ExportDocumentButton), since the current one looks a bit tight.

Also, password field modification for user (re-confirm current password, then allow user to change?) should be added.

Otherwise, looks good!

**Comment by rama-pang** [comment]
Notes:
- Haven't changed the popover design for now.
- Before editing anything, user will be prompted to re-enter their password.
- Currently there is no maximum file size limit.

**Comment by Berted** [comment]
Looks nice, albeit:
- When you press next with an empty password, it returns a generic "Error" rather than "Missing Password". A case of incomplete documentation again?
- UserButton onHover animation now no longer works, will have to fix to work with buttons.

Ready to merge, ignoring those minor issues.

**Comment by rama-pang** [comment]
For "Missing password", refer to #94.

**Review by Berted — APPROVED** [review]
Looks good. Albeit, we also need to add more code for:
- onHover animation for UserButton with images. Currently there's no animation which is not good for user feedback.
- Add img_urls to user presence avatars
- Deal with Firebase Cloud Storage rules (I think the current design for user profiles is a bit hacky and can definitely be made better, at least for cloud storage)
- Add Image option to Sign up form as well.

**Comment by rama-pang** [comment]
Notes:
- When the password is empty (on re-authentication), it seems to trigger `auth/internal-error`, which is weird(?). I manually handled the empty password case under the "Wrong password" error.
- On user button hover, I scaled it by 1.05.
- Enlarged the space between `Edit` and `Logout` button a bit.

**Comment by Berted** [comment]
Resolves #13.

**Comment by rama-pang** [comment]
The avatar file is now saved in firebase storage `users/{userID}`, which has write permissions granted only to the aforementioned user (with the same `userID`). Additionally, changing an avatar will overwrite the file, so it should be more storage-efficient.

**Comment by Berted** [comment]
Modified some stuff:
- onHover CSS animations are now slightly modified
- User Presence Avatars now also show user profile images
- Display avatar is now shown in the "Change Avatar" form

**Comment by rama-pang** [comment]
Added a `Reset` button on the change avatar input:
- If current user has an avatar, pressing `Reset` will delete the avatar (on save).
- If user uploaded an image, before saving, and pressed `Reset`, the file is reset to none. The current user avatar will also be deleted (on save).
- Note that any changes to the database will only be made on the `Save` button click.

**Comment by Berted** [comment]
Great! Everything seems to be fine now, will merge.

**Pull request merged**
