### PR TITLE
Add welcome note on sign up

### PR DESCRIPTION
**Pull request by rama-pang**
Modify the following line on `useAuth.tsx` to change the welcome note:

```tsx
const welcomeDocument = '-N7VA2xTdMSXe8UqeUmF';
```

The string should link to a public document containing the welcome note. During sign-up, the `history` of `welcomeDocument` will be copied for the (new) user's welcome note.

### CODE REVIEW

**Comment by Berted** [comment]
I'd recommend having the sample document be stored as a JSON file, as it would make other people deploying the project able to sign up new users with a sample doc immediately.

**Comment by rama-pang** [comment]
> I'd recommend having the sample document be stored as a JSON file, as it would make other people deploying the project able to sign up new users with a sample doc immediately.

As the welcome page might still be modified, maybe put this for Splashdown instead once it's finalized.

Currently, the `welcomeDocument` link is set to `docs/-N7_A0yVxAjjB-jtlQaN`.

**Review by Berted — CHANGES_REQUESTED** [review]
Make sure to also store the checkpoint from the welcome doc, since it helps optimize firepad's loading performance.

**Comment by Berted** [comment]
Will merge now as deadline is coming close. Can open another issue for Splashdown.

**Comment by Berted** [comment]
Closes #69

**Pull request merged**
